/** Compatibility re-export surface for maintained domain contracts. */
import './jsx-globals.js';
export {
  selector,
  StateSetter,
  StateTuple,
  state,
  derive,
  Derived,
  State,
  Selector,
} from './domains/state.js';
export {
  cspNonce,
  SSRStyleRegistrationValidation,
  SSRPortalState,
  DocumentRenderer,
  DeferredBoundaryRegistration,
  DocumentRenderContext,
  registerSSRStyle,
  SSRData,
  DocumentRenderArgs,
  CspNonceScope,
  SSRStyleRegistration,
} from './domains/server.js';
export {
  RenderableChild,
  ComponentFunction,
  defineScope,
  VNode,
  readScope,
  Scope,
} from './domains/context.js';
export {
  createMutation,
  createQuery,
  invalidate,
  QueryStaleReason,
  Mutation,
  createDataRuntime,
  ServerQueryRegistry,
  QueryCollection,
  defineServerQueries,
  QueryCollectionOptions,
  dehydrateDataRuntime,
  QueryConsistency,
  createQueryCollection,
  QueryScope,
  serveQuery,
  QueryPrefetchContext,
  InvalidateOptions,
  createQueryPrefetchContext,
  QueryCollectionEntry,
  prefetchQuery,
  QueryKeyPart,
  DataRuntimeOptions,
  MutationOptions,
  hydrateDataRuntime,
  QueryDefinition,
  InvalidateOnIntervalOptions,
  ServerQueryEntry,
  Query,
  DataRuntime,
  defineQuery,
  QueryCollectionKey,
  invalidateOnInterval,
  ServerQueryHandler,
  getDefaultDataRuntime,
  queryScope,
} from './domains/data.js';
export { CoreTelemetry } from './domains/telemetry.js';
export {
  RouteSnapshot,
  RouteDefinition,
  RoutePathParams,
  PageScopeRecord,
  RouteAuthResolver,
  RouteAuthOptions,
  RouteMeta,
  RouteRefSearch,
  RouteQuery,
  RouteMetaSource,
  RouteRenderResult,
  RouteRegistry,
  RouteMode,
  RouteHandler,
  RouteManifest,
  RouteComponent,
  RouteMatch,
  RouteSearchValue,
  RouteOptions,
  PageHelperOptions,
  Route,
  RouteRecord,
  RoutePolicy,
  RouteRef,
  RouteRequestResult,
  RouteRequestOptions,
  RouteSearch,
  AccessDenyStatus,
  GroupHelperOptions,
  AccessDenyDecision,
  AccessDecision,
  RouteDestination,
  RouteContext,
  AccessAllowDecision,
  RouteRegistryOptions,
  AccessRedirectDecision,
  ParsedSegment,
  LayoutScopeRecord,
  AccessRedirectStatus,
  RouteParams,
} from './domains/routing.js';
export { getSignal } from './domains/component.js';
export { scheduleEventHandler } from './domains/scheduler.js';
export {
  RuntimeKeyedReorderDecision,
  getDefaultRuntime,
  RuntimeRendererHost,
  AskrRuntime,
  AskrRuntimeOptions,
  createRuntime,
} from './domains/renderer.js';
export {
  Show,
  ShowProps,
  For,
  CaseProps,
  Match,
  MatchProps,
  ForProps,
  Case,
} from './domains/control.js';
export {
  routeActive,
  TimerOptions,
  WatchSource,
  WatchCallback,
  on,
  ActivityPredicate,
  ListenerTarget,
  capture,
  WatchValues,
  documentVisible,
  task,
  watch,
  WatchContext,
  windowFocused,
  timer,
} from './domains/lifecycle.js';
export {
  configureRenderDiagnostics,
  RenderDiagnosticsOptions,
} from './domains/diagnostics.js';
export { createRef, Ref } from './domains/refs.js';
export {
  action,
  ActionValidationError,
  ActionForm,
  defineAction,
  ActionStatus,
  ActionDescriptor,
} from './domains/actions.js';
