// Every retained 0.5.0 named/entrypoint pair is an explicit installed import.
// This fixture is copied outside the repository and compiled with TS6 and TS7.

import {
  configureRenderDiagnostics as Entry0_configureRenderDiagnostics,
  createElement as Entry0_createElement,
  createRef as Entry0_createRef,
  cspNonce as Entry0_cspNonce,
  CspNonceScope as Entry0_CspNonceScope,
  defineScope as Entry0_defineScope,
  derive as Entry0_derive,
  type Derived as Entry0_Derived,
  Fragment as Entry0_Fragment,
  getSignal as Entry0_getSignal,
  jsx as Entry0_jsx,
  jsxs as Entry0_jsxs,
  type Props as Entry0_Props,
  readScope as Entry0_readScope,
  type Ref as Entry0_Ref,
  registerSSRStyle as Entry0_registerSSRStyle,
  RenderDepthError as Entry0_RenderDepthError,
  type RenderDiagnosticsOptions as Entry0_RenderDiagnosticsOptions,
  type RenderableChild as Entry0_RenderableChild,
  type Scope as Entry0_Scope,
  selector as Entry0_selector,
  type Selector as Entry0_Selector,
  state as Entry0_state,
  type State as Entry0_State,
  type StateSetter as Entry0_StateSetter,
  type StateTuple as Entry0_StateTuple,
} from '@askrjs/askr';

import {
  cleanupApp as Entry1_cleanupApp,
  createIsland as Entry1_createIsland,
  createIslands as Entry1_createIslands,
  createSPA as Entry1_createSPA,
  hasApp as Entry1_hasApp,
  hydrateSPA as Entry1_hydrateSPA,
  type HydrateSPAConfig as Entry1_HydrateSPAConfig,
  type IslandConfig as Entry1_IslandConfig,
  type IslandsConfig as Entry1_IslandsConfig,
  type SPAConfig as Entry1_SPAConfig,
} from '@askrjs/askr/boot';

import {
  ErrorBoundary as Entry2_ErrorBoundary,
  type ErrorBoundaryFallbackRender as Entry2_ErrorBoundaryFallbackRender,
  type ErrorBoundaryProps as Entry2_ErrorBoundaryProps,
} from '@askrjs/askr/components';

import {
  Case as Entry3_Case,
  type CaseProps as Entry3_CaseProps,
  For as Entry3_For,
  type ForGetterProps as Entry3_ForGetterProps,
  type ForProps as Entry3_ForProps,
  Match as Entry3_Match,
  type MatchProps as Entry3_MatchProps,
  Show as Entry3_Show,
  type ShowProps as Entry3_ShowProps,
} from '@askrjs/askr/control';

import {
  DefaultPortal as Entry4_DefaultPortal,
  definePortal as Entry4_definePortal,
  type JSXElement as Entry4_JSXElement,
  layout as Entry4_layout,
  type LayoutComponent as Entry4_LayoutComponent,
  Portal as Entry4_Portal,
  type PortalProps as Entry4_PortalProps,
  Presence as Entry4_Presence,
  type PresenceProps as Entry4_PresenceProps,
  Slot as Entry4_Slot,
  type SlotProps as Entry4_SlotProps,
} from '@askrjs/askr/foundations';

import {
  composeHandlers as Entry5_composeHandlers,
  type ComposeHandlersOptions as Entry5_ComposeHandlersOptions,
  composeRefs as Entry5_composeRefs,
  formatId as Entry5_formatId,
  type FormatIdOptions as Entry5_FormatIdOptions,
  type MergedProps as Entry5_MergedProps,
  mergeProps as Entry5_mergeProps,
  type Ref as Entry5_Ref,
  setRef as Entry5_setRef,
} from '@askrjs/askr/foundations/utilities';

import {
  applyInteractionPolicy as Entry6_applyInteractionPolicy,
  dismissable as Entry6_dismissable,
  type DismissableOptions as Entry6_DismissableOptions,
  focusable as Entry6_focusable,
  type FocusableOptions as Entry6_FocusableOptions,
  type FocusableResult as Entry6_FocusableResult,
  hoverable as Entry6_hoverable,
  type HoverableOptions as Entry6_HoverableOptions,
  type HoverableResult as Entry6_HoverableResult,
  type InteractionPolicyInput as Entry6_InteractionPolicyInput,
  mergeInteractionProps as Entry6_mergeInteractionProps,
  type Orientation as Entry6_Orientation,
  pressable as Entry6_pressable,
  type PressableOptions as Entry6_PressableOptions,
  type PressableResult as Entry6_PressableResult,
  rovingFocus as Entry6_rovingFocus,
  type RovingFocusOptions as Entry6_RovingFocusOptions,
  type RovingFocusResult as Entry6_RovingFocusResult,
} from '@askrjs/askr/foundations/interactions';

import {
  controllableState as Entry7_controllableState,
  type ControllableState as Entry7_ControllableState,
} from '@askrjs/askr/foundations/state';

import {
  cloneElement as Entry8_cloneElement,
  type Collection as Entry8_Collection,
  type CollectionItem as Entry8_CollectionItem,
  createCollection as Entry8_createCollection,
  DefaultPortal as Entry8_DefaultPortal,
  definePortal as Entry8_definePortal,
  isElement as Entry8_isElement,
  type JSXElement as Entry8_JSXElement,
  layout as Entry8_layout,
  type LayoutComponent as Entry8_LayoutComponent,
  Portal as Entry8_Portal,
  type PortalProps as Entry8_PortalProps,
  Presence as Entry8_Presence,
  type PresenceProps as Entry8_PresenceProps,
  Slot as Entry8_Slot,
  type SlotProps as Entry8_SlotProps,
} from '@askrjs/askr/foundations/structures';

import {
  IconBase as Entry9_IconBase,
  type IconOwnProps as Entry9_IconOwnProps,
  type IconProps as Entry9_IconProps,
  type IconSizeToken as Entry9_IconSizeToken,
  type IconStyleObject as Entry9_IconStyleObject,
} from '@askrjs/askr/foundations/icon';

import {
  type ActivityPredicate as Entry10_ActivityPredicate,
  capture as Entry10_capture,
  documentVisible as Entry10_documentVisible,
  type ListenerTarget as Entry10_ListenerTarget,
  on as Entry10_on,
  resource as Entry10_resource,
  type ResourceResult as Entry10_ResourceResult,
  routeActive as Entry10_routeActive,
  stream as Entry10_stream,
  type StreamOptions as Entry10_StreamOptions,
  type StreamResult as Entry10_StreamResult,
  type StreamStatus as Entry10_StreamStatus,
  task as Entry10_task,
  timer as Entry10_timer,
  type TimerOptions as Entry10_TimerOptions,
  watch as Entry10_watch,
  type WatchCallback as Entry10_WatchCallback,
  type WatchContext as Entry10_WatchContext,
  type WatchSource as Entry10_WatchSource,
  type WatchValues as Entry10_WatchValues,
  windowFocused as Entry10_windowFocused,
} from '@askrjs/askr/resources';

import {
  createDataRuntime as Entry11_createDataRuntime,
  disposeDataRuntime as Entry11_disposeDataRuntime,
  createMutation as Entry11_createMutation,
  createQuery as Entry11_createQuery,
  createQueryCollection as Entry11_createQueryCollection,
  createQueryPrefetchContext as Entry11_createQueryPrefetchContext,
  type DataRuntime as Entry11_DataRuntime,
  type DataRuntimeOptions as Entry11_DataRuntimeOptions,
  defineQuery as Entry11_defineQuery,
  defineServerQueries as Entry11_defineServerQueries,
  dehydrateDataRuntime as Entry11_dehydrateDataRuntime,
  getDefaultDataRuntime as Entry11_getDefaultDataRuntime,
  hydrateDataRuntime as Entry11_hydrateDataRuntime,
  invalidate as Entry11_invalidate,
  invalidateOnInterval as Entry11_invalidateOnInterval,
  type InvalidateOnIntervalOptions as Entry11_InvalidateOnIntervalOptions,
  type InvalidateOptions as Entry11_InvalidateOptions,
  type Mutation as Entry11_Mutation,
  type MutationOptions as Entry11_MutationOptions,
  prefetchQuery as Entry11_prefetchQuery,
  type Query as Entry11_Query,
  type QueryCollection as Entry11_QueryCollection,
  type QueryCollectionEntry as Entry11_QueryCollectionEntry,
  type QueryCollectionKey as Entry11_QueryCollectionKey,
  type QueryCollectionOptions as Entry11_QueryCollectionOptions,
  type QueryConsistency as Entry11_QueryConsistency,
  type QueryDefinition as Entry11_QueryDefinition,
  type QueryKeyPart as Entry11_QueryKeyPart,
  type QueryPrefetchContext as Entry11_QueryPrefetchContext,
  queryScope as Entry11_queryScope,
  type QueryScope as Entry11_QueryScope,
  type QueryStaleReason as Entry11_QueryStaleReason,
  refreshOnActivity as Entry11_refreshOnActivity,
  type RefreshOnActivityOptions as Entry11_RefreshOnActivityOptions,
  serveQuery as Entry11_serveQuery,
  type ServerQueryEntry as Entry11_ServerQueryEntry,
  type ServerQueryHandler as Entry11_ServerQueryHandler,
  type ServerQueryRegistry as Entry11_ServerQueryRegistry,
} from '@askrjs/askr/data';

import {
  cleanup as Entry12_cleanup,
  click as Entry12_click,
  createInvalidationRecorder as Entry12_createInvalidationRecorder,
  createMutationTestRegistry as Entry12_createMutationTestRegistry,
  createQueryTestRegistry as Entry12_createQueryTestRegistry,
  dispatch as Entry12_dispatch,
  flush as Entry12_flush,
  getRouteWarnings as Entry12_getRouteWarnings,
  type InvalidationRecord as Entry12_InvalidationRecord,
  type InvalidationRecorder as Entry12_InvalidationRecorder,
  mockQuery as Entry12_mockQuery,
  type MockQueryOptions as Entry12_MockQueryOptions,
  type MockRefresh as Entry12_MockRefresh,
  type MutationFixture as Entry12_MutationFixture,
  type MutationFixtureInitial as Entry12_MutationFixtureInitial,
  mutationState as Entry12_mutationState,
  type MutationTestRegistry as Entry12_MutationTestRegistry,
  type QueryTestRegistry as Entry12_QueryTestRegistry,
  render as Entry12_render,
  type RenderOptions as Entry12_RenderOptions,
  type RenderResult as Entry12_RenderResult,
  renderRoute as Entry12_renderRoute,
  type RoutePatternWarning as Entry12_RoutePatternWarning,
  type RouteRenderOptions as Entry12_RouteRenderOptions,
  submit as Entry12_submit,
  type as Entry12_type,
} from '@askrjs/askr/testing';

import {
  debounceEvent as Entry13_debounceEvent,
  idle as Entry13_idle,
  once as Entry13_once,
  raf as Entry13_raf,
  rafEvent as Entry13_rafEvent,
  retry as Entry13_retry,
  type RetryOptions as Entry13_RetryOptions,
  type RetryOutcome as Entry13_RetryOutcome,
  scheduleEventHandler as Entry13_scheduleEventHandler,
  scheduleIdle as Entry13_scheduleIdle,
  scheduleRetry as Entry13_scheduleRetry,
  scheduleTimeout as Entry13_scheduleTimeout,
  throttle as Entry13_throttle,
  throttleEvent as Entry13_throttleEvent,
  type ThrottleOptions as Entry13_ThrottleOptions,
  timeout as Entry13_timeout,
} from '@askrjs/askr/fx';

import {
  type AccessDecision as Entry14_AccessDecision,
  type AccessDenyDecision as Entry14_AccessDenyDecision,
  type AccessRedirectDecision as Entry14_AccessRedirectDecision,
  allow as Entry14_allow,
  createRouteRegistry as Entry14_createRouteRegistry,
  currentAuth as Entry14_currentAuth,
  currentRoute as Entry14_currentRoute,
  defer as Entry14_defer,
  type Deferred as Entry14_Deferred,
  type DeferredState as Entry14_DeferredState,
  deny as Entry14_deny,
  fallback as Entry14_fallback,
  forbidden as Entry14_forbidden,
  group as Entry14_group,
  type GroupHelperOptions as Entry14_GroupHelperOptions,
  type HistoryScrollBehavior as Entry14_HistoryScrollBehavior,
  index as Entry14_index,
  isDeferred as Entry14_isDeferred,
  lazy as Entry14_lazy,
  type LazyRouteComponent as Entry14_LazyRouteComponent,
  lazyRouteData as Entry14_lazyRouteData,
  type LazyRouteDataLoader as Entry14_LazyRouteDataLoader,
  Link as Entry14_Link,
  type LinkProps as Entry14_LinkProps,
  matchRoute as Entry14_matchRoute,
  navigate as Entry14_navigate,
  type NavigateOptions as Entry14_NavigateOptions,
  type NavigationScrollBehavior as Entry14_NavigationScrollBehavior,
  notFound as Entry14_notFound,
  onRouteChange as Entry14_onRouteChange,
  Outlet as Entry14_Outlet,
  page as Entry14_page,
  type PageHelperOptions as Entry14_PageHelperOptions,
  reconcileRouteMeta as Entry14_reconcileRouteMeta,
  redirect as Entry14_redirect,
  Resolve as Entry14_Resolve,
  resolveDeferredValues as Entry14_resolveDeferredValues,
  type ResolveProps as Entry14_ResolveProps,
  resolveRouteMeta as Entry14_resolveRouteMeta,
  resolveRouteRequest as Entry14_resolveRouteRequest,
  route as Entry14_route,
  type Route as Entry14_Route,
  type RouteAuthOptions as Entry14_RouteAuthOptions,
  type RouteAuthResolver as Entry14_RouteAuthResolver,
  type RouteChangeCleanup as Entry14_RouteChangeCleanup,
  type RouteChangeOptions as Entry14_RouteChangeOptions,
  type RouteComponent as Entry14_RouteComponent,
  type RouteContext as Entry14_RouteContext,
  routeData as Entry14_routeData,
  RouteDataLoadError as Entry14_RouteDataLoadError,
  type RouteDataLoadPhase as Entry14_RouteDataLoadPhase,
  type RouteDefinition as Entry14_RouteDefinition,
  type RouteDestination as Entry14_RouteDestination,
  type RouteHandler as Entry14_RouteHandler,
  type RouteManifest as Entry14_RouteManifest,
  type RouteMatch as Entry14_RouteMatch,
  type RouteMeta as Entry14_RouteMeta,
  type RouteMetaSource as Entry14_RouteMetaSource,
  type RouteMode as Entry14_RouteMode,
  type RouteOptions as Entry14_RouteOptions,
  type RouteParams as Entry14_RouteParams,
  type RoutePathParams as Entry14_RoutePathParams,
  type RoutePolicy as Entry14_RoutePolicy,
  type RouteQuery as Entry14_RouteQuery,
  type RouteQueryParamInput as Entry14_RouteQueryParamInput,
  type RouteQueryParamValue as Entry14_RouteQueryParamValue,
  type RouteQueryUpdater as Entry14_RouteQueryUpdater,
  type RouteQueryUpdates as Entry14_RouteQueryUpdates,
  type RouteRecord as Entry14_RouteRecord,
  type RouteRef as Entry14_RouteRef,
  type RouteRegistry as Entry14_RouteRegistry,
  type RouteRegistryOptions as Entry14_RouteRegistryOptions,
  type RouteRenderResult as Entry14_RouteRenderResult,
  type RouteRequestOptions as Entry14_RouteRequestOptions,
  type RouteRequestResult as Entry14_RouteRequestResult,
  type RouteSearch as Entry14_RouteSearch,
  type RouteSearchValue as Entry14_RouteSearchValue,
  type RouteSnapshot as Entry14_RouteSnapshot,
  type ScrollRestorationOptions as Entry14_ScrollRestorationOptions,
  serializeRouteMeta as Entry14_serializeRouteMeta,
  to as Entry14_to,
  unauthorized as Entry14_unauthorized,
  updateRouteQuery as Entry14_updateRouteQuery,
  type UpdateRouteQueryOptions as Entry14_UpdateRouteQueryOptions,
} from '@askrjs/askr/router';

import {
  action as Entry15_action,
  type ActionDescriptor as Entry15_ActionDescriptor,
  ActionForm as Entry15_ActionForm,
  type ActionStatus as Entry15_ActionStatus,
  type ActionValidationError as Entry15_ActionValidationError,
  defineAction as Entry15_defineAction,
} from '@askrjs/askr/actions';

import {
  createRenderContext as Entry16_createRenderContext,
  type DocumentRenderArgs as Entry16_DocumentRenderArgs,
  type DocumentRenderContext as Entry16_DocumentRenderContext,
  type DocumentRenderer as Entry16_DocumentRenderer,
  escapeHtml as Entry16_escapeHtml,
  getRenderContext as Entry16_getRenderContext,
  renderRouteRequest as Entry16_renderRouteRequest,
  type RenderRouteRequestOptions as Entry16_RenderRouteRequestOptions,
  type RenderRouteRequestResult as Entry16_RenderRouteRequestResult,
  renderRouteRequestToString as Entry16_renderRouteRequestToString,
  renderToStream as Entry16_renderToStream,
  renderToString as Entry16_renderToString,
  renderToStringSync as Entry16_renderToStringSync,
  SSRAccessDecisionError as Entry16_SSRAccessDecisionError,
  type SSRComponent as Entry16_SSRComponent,
  SSRDataMissingError as Entry16_SSRDataMissingError,
  type SSRStyleRegistration as Entry16_SSRStyleRegistration,
  type SSRStyleRegistrationValidation as Entry16_SSRStyleRegistrationValidation,
  type VNode as Entry16_VNode,
  withRenderContext as Entry16_withRenderContext,
  withRenderContextAsync as Entry16_withRenderContextAsync,
} from '@askrjs/askr/ssr';

import {
  createStaticGen as Entry17_createStaticGen,
  type DocumentRenderArgs as Entry17_DocumentRenderArgs,
  type DocumentRenderContext as Entry17_DocumentRenderContext,
  type DocumentRenderer as Entry17_DocumentRenderer,
  type RouteRenderReason as Entry17_RouteRenderReason,
  type RouteRenderResult as Entry17_RouteRenderResult,
  type RouteRenderStatus as Entry17_RouteRenderStatus,
  type SSGAssetSource as Entry17_SSGAssetSource,
  type SSGGenerateOptions as Entry17_SSGGenerateOptions,
  type SSGMetadata as Entry17_SSGMetadata,
  type SSGMode as Entry17_SSGMode,
  type SSGOptions as Entry17_SSGOptions,
  type SSGResult as Entry17_SSGResult,
} from '@askrjs/askr/ssg';

import {
  Fragment as Entry18_Fragment,
  jsx as Entry18_jsx,
  type JSX as Entry18_JSX,
  type JSXComponent as Entry18_JSXComponent,
  type JSXElement as Entry18_JSXElement,
  type JSXElementType as Entry18_JSXElementType,
  jsxs as Entry18_jsxs,
} from '@askrjs/askr/jsx-runtime';

import {
  Fragment as Entry19_Fragment,
  type JSX as Entry19_JSX,
  jsxDEV as Entry19_jsxDEV,
} from '@askrjs/askr/jsx-dev-runtime';

export const retainedValues = [
  Entry0_configureRenderDiagnostics,
  Entry0_createElement,
  Entry0_createRef,
  Entry0_cspNonce,
  Entry0_CspNonceScope,
  Entry0_defineScope,
  Entry0_derive,
  Entry0_Fragment,
  Entry0_getSignal,
  Entry0_jsx,
  Entry0_jsxs,
  Entry0_readScope,
  Entry0_registerSSRStyle,
  Entry0_RenderDepthError,
  Entry0_selector,
  Entry0_state,
  Entry1_cleanupApp,
  Entry1_createIsland,
  Entry1_createIslands,
  Entry1_createSPA,
  Entry1_hasApp,
  Entry1_hydrateSPA,
  Entry2_ErrorBoundary,
  Entry3_Case,
  Entry3_For,
  Entry3_Match,
  Entry3_Show,
  Entry4_DefaultPortal,
  Entry4_definePortal,
  Entry4_layout,
  Entry4_Portal,
  Entry4_Presence,
  Entry4_Slot,
  Entry5_composeHandlers,
  Entry5_composeRefs,
  Entry5_formatId,
  Entry5_mergeProps,
  Entry5_setRef,
  Entry6_applyInteractionPolicy,
  Entry6_dismissable,
  Entry6_focusable,
  Entry6_hoverable,
  Entry6_mergeInteractionProps,
  Entry6_pressable,
  Entry6_rovingFocus,
  Entry7_controllableState,
  Entry8_cloneElement,
  Entry8_createCollection,
  Entry8_DefaultPortal,
  Entry8_definePortal,
  Entry8_isElement,
  Entry8_layout,
  Entry8_Portal,
  Entry8_Presence,
  Entry8_Slot,
  Entry9_IconBase,
  Entry10_capture,
  Entry10_documentVisible,
  Entry10_on,
  Entry10_resource,
  Entry10_routeActive,
  Entry10_stream,
  Entry10_task,
  Entry10_timer,
  Entry10_watch,
  Entry10_windowFocused,
  Entry11_createDataRuntime,
  Entry11_disposeDataRuntime,
  Entry11_createMutation,
  Entry11_createQuery,
  Entry11_createQueryCollection,
  Entry11_createQueryPrefetchContext,
  Entry11_defineQuery,
  Entry11_defineServerQueries,
  Entry11_dehydrateDataRuntime,
  Entry11_getDefaultDataRuntime,
  Entry11_hydrateDataRuntime,
  Entry11_invalidate,
  Entry11_invalidateOnInterval,
  Entry11_prefetchQuery,
  Entry11_queryScope,
  Entry11_refreshOnActivity,
  Entry11_serveQuery,
  Entry12_cleanup,
  Entry12_click,
  Entry12_createInvalidationRecorder,
  Entry12_createMutationTestRegistry,
  Entry12_createQueryTestRegistry,
  Entry12_dispatch,
  Entry12_flush,
  Entry12_getRouteWarnings,
  Entry12_mockQuery,
  Entry12_mutationState,
  Entry12_render,
  Entry12_renderRoute,
  Entry12_submit,
  Entry12_type,
  Entry13_debounceEvent,
  Entry13_idle,
  Entry13_once,
  Entry13_raf,
  Entry13_rafEvent,
  Entry13_retry,
  Entry13_scheduleEventHandler,
  Entry13_scheduleIdle,
  Entry13_scheduleRetry,
  Entry13_scheduleTimeout,
  Entry13_throttle,
  Entry13_throttleEvent,
  Entry13_timeout,
  Entry14_allow,
  Entry14_createRouteRegistry,
  Entry14_currentAuth,
  Entry14_currentRoute,
  Entry14_defer,
  Entry14_deny,
  Entry14_fallback,
  Entry14_forbidden,
  Entry14_group,
  Entry14_index,
  Entry14_isDeferred,
  Entry14_lazy,
  Entry14_lazyRouteData,
  Entry14_Link,
  Entry14_matchRoute,
  Entry14_navigate,
  Entry14_notFound,
  Entry14_onRouteChange,
  Entry14_Outlet,
  Entry14_page,
  Entry14_reconcileRouteMeta,
  Entry14_redirect,
  Entry14_Resolve,
  Entry14_resolveDeferredValues,
  Entry14_resolveRouteMeta,
  Entry14_resolveRouteRequest,
  Entry14_route,
  Entry14_routeData,
  Entry14_RouteDataLoadError,
  Entry14_serializeRouteMeta,
  Entry14_to,
  Entry14_unauthorized,
  Entry14_updateRouteQuery,
  Entry15_action,
  Entry15_ActionForm,
  Entry15_defineAction,
  Entry16_createRenderContext,
  Entry16_escapeHtml,
  Entry16_getRenderContext,
  Entry16_renderRouteRequest,
  Entry16_renderRouteRequestToString,
  Entry16_renderToStream,
  Entry16_renderToString,
  Entry16_renderToStringSync,
  Entry16_SSRAccessDecisionError,
  Entry16_SSRDataMissingError,
  Entry16_withRenderContext,
  Entry16_withRenderContextAsync,
  Entry17_createStaticGen,
  Entry18_Fragment,
  Entry18_jsx,
  Entry18_jsxs,
  Entry19_Fragment,
  Entry19_jsxDEV,
];

export type {
  Entry0_Derived,
  Entry0_Props,
  Entry0_Ref,
  Entry0_RenderDiagnosticsOptions,
  Entry0_RenderableChild,
  Entry0_Scope,
  Entry0_Selector,
  Entry0_State,
  Entry0_StateSetter,
  Entry0_StateTuple,
  Entry1_HydrateSPAConfig,
  Entry1_IslandConfig,
  Entry1_IslandsConfig,
  Entry1_SPAConfig,
  Entry2_ErrorBoundaryFallbackRender,
  Entry2_ErrorBoundaryProps,
  Entry3_CaseProps,
  Entry3_ForGetterProps,
  Entry3_ForProps,
  Entry3_MatchProps,
  Entry3_ShowProps,
  Entry4_JSXElement,
  Entry4_LayoutComponent,
  Entry4_PortalProps,
  Entry4_PresenceProps,
  Entry4_SlotProps,
  Entry5_ComposeHandlersOptions,
  Entry5_FormatIdOptions,
  Entry5_MergedProps,
  Entry5_Ref,
  Entry6_DismissableOptions,
  Entry6_FocusableOptions,
  Entry6_FocusableResult,
  Entry6_HoverableOptions,
  Entry6_HoverableResult,
  Entry6_InteractionPolicyInput,
  Entry6_Orientation,
  Entry6_PressableOptions,
  Entry6_PressableResult,
  Entry6_RovingFocusOptions,
  Entry6_RovingFocusResult,
  Entry7_ControllableState,
  Entry8_Collection,
  Entry8_CollectionItem,
  Entry8_JSXElement,
  Entry8_LayoutComponent,
  Entry8_PortalProps,
  Entry8_PresenceProps,
  Entry8_SlotProps,
  Entry9_IconOwnProps,
  Entry9_IconProps,
  Entry9_IconSizeToken,
  Entry9_IconStyleObject,
  Entry10_ActivityPredicate,
  Entry10_ListenerTarget,
  Entry10_ResourceResult,
  Entry10_StreamOptions,
  Entry10_StreamResult,
  Entry10_StreamStatus,
  Entry10_TimerOptions,
  Entry10_WatchCallback,
  Entry10_WatchContext,
  Entry10_WatchSource,
  Entry10_WatchValues,
  Entry11_DataRuntime,
  Entry11_DataRuntimeOptions,
  Entry11_InvalidateOnIntervalOptions,
  Entry11_InvalidateOptions,
  Entry11_Mutation,
  Entry11_MutationOptions,
  Entry11_Query,
  Entry11_QueryCollection,
  Entry11_QueryCollectionEntry,
  Entry11_QueryCollectionKey,
  Entry11_QueryCollectionOptions,
  Entry11_QueryConsistency,
  Entry11_QueryDefinition,
  Entry11_QueryKeyPart,
  Entry11_QueryPrefetchContext,
  Entry11_QueryScope,
  Entry11_QueryStaleReason,
  Entry11_RefreshOnActivityOptions,
  Entry11_ServerQueryEntry,
  Entry11_ServerQueryHandler,
  Entry11_ServerQueryRegistry,
  Entry12_InvalidationRecord,
  Entry12_InvalidationRecorder,
  Entry12_MockQueryOptions,
  Entry12_MockRefresh,
  Entry12_MutationFixture,
  Entry12_MutationFixtureInitial,
  Entry12_MutationTestRegistry,
  Entry12_QueryTestRegistry,
  Entry12_RenderOptions,
  Entry12_RenderResult,
  Entry12_RoutePatternWarning,
  Entry12_RouteRenderOptions,
  Entry13_RetryOptions,
  Entry13_RetryOutcome,
  Entry13_ThrottleOptions,
  Entry14_AccessDecision,
  Entry14_AccessDenyDecision,
  Entry14_AccessRedirectDecision,
  Entry14_Deferred,
  Entry14_DeferredState,
  Entry14_GroupHelperOptions,
  Entry14_HistoryScrollBehavior,
  Entry14_LazyRouteComponent,
  Entry14_LazyRouteDataLoader,
  Entry14_LinkProps,
  Entry14_NavigateOptions,
  Entry14_NavigationScrollBehavior,
  Entry14_PageHelperOptions,
  Entry14_ResolveProps,
  Entry14_Route,
  Entry14_RouteAuthOptions,
  Entry14_RouteAuthResolver,
  Entry14_RouteChangeCleanup,
  Entry14_RouteChangeOptions,
  Entry14_RouteComponent,
  Entry14_RouteContext,
  Entry14_RouteDataLoadPhase,
  Entry14_RouteDefinition,
  Entry14_RouteDestination,
  Entry14_RouteHandler,
  Entry14_RouteManifest,
  Entry14_RouteMatch,
  Entry14_RouteMeta,
  Entry14_RouteMetaSource,
  Entry14_RouteMode,
  Entry14_RouteOptions,
  Entry14_RouteParams,
  Entry14_RoutePathParams,
  Entry14_RoutePolicy,
  Entry14_RouteQuery,
  Entry14_RouteQueryParamInput,
  Entry14_RouteQueryParamValue,
  Entry14_RouteQueryUpdater,
  Entry14_RouteQueryUpdates,
  Entry14_RouteRecord,
  Entry14_RouteRef,
  Entry14_RouteRegistry,
  Entry14_RouteRegistryOptions,
  Entry14_RouteRenderResult,
  Entry14_RouteRequestOptions,
  Entry14_RouteRequestResult,
  Entry14_RouteSearch,
  Entry14_RouteSearchValue,
  Entry14_RouteSnapshot,
  Entry14_ScrollRestorationOptions,
  Entry14_UpdateRouteQueryOptions,
  Entry15_ActionDescriptor,
  Entry15_ActionStatus,
  Entry15_ActionValidationError,
  Entry16_DocumentRenderArgs,
  Entry16_DocumentRenderContext,
  Entry16_DocumentRenderer,
  Entry16_RenderRouteRequestOptions,
  Entry16_RenderRouteRequestResult,
  Entry16_SSRComponent,
  Entry16_SSRStyleRegistration,
  Entry16_SSRStyleRegistrationValidation,
  Entry16_VNode,
  Entry17_DocumentRenderArgs,
  Entry17_DocumentRenderContext,
  Entry17_DocumentRenderer,
  Entry17_RouteRenderReason,
  Entry17_RouteRenderResult,
  Entry17_RouteRenderStatus,
  Entry17_SSGAssetSource,
  Entry17_SSGGenerateOptions,
  Entry17_SSGMetadata,
  Entry17_SSGMode,
  Entry17_SSGOptions,
  Entry17_SSGResult,
  Entry18_JSX,
  Entry18_JSXComponent,
  Entry18_JSXElement,
  Entry18_JSXElementType,
  Entry19_JSX,
};

export type JSXNamespaceElement0 = Entry18_JSX.Element;
export type JSXNamespaceElement1 = Entry19_JSX.Element;
